<a href="https://colab.research.google.com/github/DheerajGolla9/PDS/blob/main/PDS_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset

In [108]:
df = pd.read_csv('https://raw.githubusercontent.com/datasets/hepatitis/master/data/hepatitis.csv')

# Displaying the first few rows of the DataFrame

In [109]:
print("Original DataFrame (first 10 rows):")
df.head(10)

Original DataFrame (first 10 rows):

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95.0,28.0,4.0,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,NaN,NaN,NaN,NaN,NaN,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,NaN,NaN,NaN,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,NaN,48.0,4.4,NaN,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,120.0,3.9,NaN,False,live

# Printing the data types to verify the column types

In [110]:
print("Missing values before handling:")
print(df.isnull().sum())

Missing values before handling:
age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

In [111]:
print("Data types of each column:")
df.dtypes

Data types of each column:

age                  int64
sex                 object
steroid             object
antivirals            bool
fatigue             object
malaise             object
anorexia            object
liver_big           object
liver_firm          object
spleen_palpable     object
spiders             object
ascites             object
varices             object
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
protime            float64
histology             bool
class               object
dtype: object

# Step 2: Select numeric columns

In [112]:
numeric_df = df.select_dtypes(include=np.number).copy()

# Verifying the data types of numeric columns

In [113]:
print("Data types of numeric columns:")
numeric_df.dtypes

Data types of numeric columns:

age                int64
bilirubin        float64
alk_phosphate    float64
sgot             float64
albumin          float64
protime          float64
dtype: object

# Printing the numeric columns

In [114]:
print(numeric_df.head(10))

   age  bilirubin  alk_phosphate   sgot  albumin  protime
0   30        1.0           85.0   18.0      4.0      NaN
1   50        0.9          135.0   42.0      3.5      NaN
2   78        0.7           96.0   32.0      4.0      NaN
3   31        0.7           46.0   52.0      4.0     80.0
4   34        1.0            NaN  200.0      4.0      NaN
5   34        0.9           95.0   28.0      4.0     75.0
6   51        NaN            NaN    NaN      NaN      NaN
7   23        1.0            NaN    NaN      NaN      NaN
8   39        0.7            NaN   48.0      4.4      NaN
9   30        1.0            NaN  120.0      3.9      NaN

# Step 3: Calculating the mean of each numeric column

In [115]:
mean_values = numeric_df.mean()

# Printing the calculated mean values for each numeric column

In [116]:
print("Calculated mean values for each numeric column:")
print(mean_values)

Calculated mean values for each numeric column:
age               41.200000
bilirubin          1.427517
alk_phosphate    105.325397
sgot              85.894040
albumin            3.817266
protime           61.852273
dtype: float64

# Step 4: Filling missing values with the mean

In [117]:
numeric_df.fillna(mean_values, inplace=True)

# Printing the DataFrame after replacing missing values with the mean

In [118]:
print("Numeric DataFrame after filling missing values with mean:")
numeric_df.head(10)

Numeric DataFrame after filling missing values with mean:

   age  bilirubin  alk_phosphate       sgot   albumin    protime
0   30   1.000000      85.000000   18.00000  4.000000  61.852273
1   50   0.900000     135.000000   42.00000  3.500000  61.852273
2   78   0.700000      96.000000   32.00000  4.000000  61.852273
3   31   0.700000      46.000000   52.00000  4.000000  80.000000
4   34   1.000000     105.325397  200.00000  4.000000  61.852273
5   34   0.900000      95.000000   28.00000  4.000000  75.000000
6   51   1.427517     105.325397   85.89404  3.817266  61.852273
7   23   1.000000     105.325397   85.89404  3.817266  61.852273
8   39   0.700000     105.325397   48.00000  4.400000  61.852273
9   30   1.000000     105.325397  120.00000  3.900000  61.852273

In [119]:
print(numeric_df.dtypes)

age                int64
bilirubin        float64
alk_phosphate    float64
sgot             float64
albumin          float64
protime          float64
dtype: object

# Step 5: Updating the original DataFrame with the modified numeric columns

In [120]:
df[numeric_df.columns] = numeric_df
df.head(10)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.000000,85.000000,18.00000,4.000000,61.852273,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.900000,135.000000,42.00000,3.500000,61.852273,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.700000,96.000000,32.00000,4.000000,61.852273,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.700000,46.000000,52.00000,4.000000,80.000000,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.000000,105.325397,200.00000,4.000000,61.852273,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.900000,95.000000,28.00000,4.000000,75.000000,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,1.427517,105.325397,85.89404,3.817266,61.852273,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.000000,105.325397,85.89404,3.817266,61.852273,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.700000,105.325397,48.00000,4.400000,61.852273,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.000000,105.325397,120.00000,3.900000,61.852273,False,live

# Step 6: Selecting and updating non-numeric columns to Original DataFrame

In [123]:
boolean_cols = df.select_dtypes(include=['object', 'bool']).columns
df[boolean_cols] = df[boolean_cols].apply(lambda col: col.fillna(col.mode()[0]).astype(str))

#Verifying the Missing values after handling

In [122]:
print("Missing values after handling:")
print(df.isnull().sum())

Missing values after handling:
age                0
sex                0
steroid            0
antivirals         0
fatigue            0
malaise            0
anorexia           0
liver_big          0
liver_firm         0
spleen_palpable    0
spiders            0
ascites            0
varices            0
bilirubin          0
alk_phosphate      0
sgot               0
albumin            0
protime            0
histology          0
class              0
dtype: int64

#Printing cleaned DataFrame

In [124]:
df.head(10)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.000000,85.000000,18.00000,4.000000,61.852273,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.900000,135.000000,42.00000,3.500000,61.852273,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.700000,96.000000,32.00000,4.000000,61.852273,False,live
3,31,female,True,True,False,False,False,True,False,False,False,False,False,0.700000,46.000000,52.00000,4.000000,80.000000,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.000000,105.325397,200.00000,4.000000,61.852273,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.900000,95.000000,28.00000,4.000000,75.000000,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,1.427517,105.325397,85.89404,3.817266,61.852273,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.000000,105.325397,85.89404,3.817266,61.852273,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.700000,105.325397,48.00000,4.400000,61.852273,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.000000,105.325397,120.00000,3.900000,61.852273,False,live